### ISSUE TITLE
Hierarchical Transformer with Dynamic Groups

### ISSUE THREAD

**Issue by PiotrNawrot** [lucidrains/simple-hierarchical-transformer#2]
Great work!
You can take a look at this recent work that improves upon Hourglass and instead of Fixed Groupings they learn how to shorten the sequence dynamically (based on the input sequence), along with the model, and directly from the data: [Dynamic Pooling](https://arxiv.org/abs/2211.09761)

**Comment by lucidrains** [comment]
@PiotrNawrot oh very cool Piotr! my idea isn't this complex, though the paper is very interesting and will definitely bookmark for future reading
